### ISSUE TITLE
Add demo mode for app review process

### ISSUE THREAD

**Issue by kelada** [getsenic/senic-home-automation-app#34]
We require a method to show the functionality of the application during the review process, this means creating a demo mode that can be access via an invisible button that will be tapped 10 times from the "Getting Started" screen.

**Comment by rudolfs** [comment]
"If features require an environment that is hard to replicate or require specific hardware, be prepared to provide a demo video or the hardware."
https://developer.apple.com/app-store/review/rejections

2.3.1 Don’t include any hidden or undocumented features in your app; your app’s functionality should be clear to end-users and App Review.
https://developer.apple.com/app-store/review/guidelines

**Comment by kelada** [comment]
Sounds good, we can revisit if needed, for now I'll close this.
