### ISSUE TITLE
Implement "Hub Settings" screen

### ISSUE THREAD

**Issue by rudolfs** [getsenic/senic-home-automation-app#38]
- [x] "Factory reset" (resets hub and app, make sure it works when hub is unreachable)
- [x] Ask user for confirmation when doing  a factory reset
- [x] Display mobile app version
- [x] Display Senic Hub OS version
- [x] Display wifi network name the hub is connected to

**Comment by rudolfs** [comment]
https://github.com/getsenic/senic-home-automation-app/commit/c1c633d31f28d2a367dce5a71d9f6c29e282b99e
https://github.com/getsenic/senic-home-automation-app/commit/0c38755d59c09ea08cad37909c8ba353aff82b76

**Comment by kelada** [comment]
👍
