### ISSUE TITLE
Regressions in "Simplify hub discovery screen"

### ISSUE THREAD

**Issue by kelada** [getsenic/senic-home-automation-app#5]
1. ~~This does not support adding multiple nuimos from the tabbed part of the app~~
1. There is a noticeable regression in the discovery time and process of nuimos. It will find a nuimo, connected to it, show the tick on it and then go back to flashing the bluetooth logo, it does this mulitple times @commento has also experienced this.

Commit: 6d9f9da

**Comment by rudolfs** [comment]
The commit was rolled back, we'll try a different solution.
